### ISSUE TITLE
how about Gradle?

### ISSUE THREAD

**Issue by include** [korfuri/awesome-monorepo#11]
Hi,

I think https://github.com/gradle/gradle is another alternative to build systems isn't it?

Cheers,
Francisco

**Comment by korfuri** [comment]
I'm not familiar with Gradle, so I can't personally comment. Do you have experience using it in a monorepo?

**Comment by borjapazr** [comment]
And Maven? It is similar to Gradle.

**Comment by include** [comment]
Hi. Unfortunately I don't. I came to "awesome-monorepo" seeking enlightenment :)
