### ISSUE TITLE
Lists of pros and cons?

### ISSUE THREAD

**Issue by dandv** [korfuri/awesome-monorepo#20]
Would love to see a comprehensive list of pros and cons of monorepos.

In particular, I'm concerned about security - if a large company needs to hire a contractor to work on the design of some web app, why would they want to give that contractor access to the entire repo, instead of just to the front-end code?

This [Hacker News thread](https://news.ycombinator.com/item?id=14662312) touched a bit upon the issue of risk, but the matter was hand-waved ("You should trust every developer"). [These](https://softwareengineering.stackexchange.com/questions/373310/how-to-split-a-monorepo-accross-multiple-teams-each-has-access-to-only-a-slice-o) SE.stackexchange [questions](https://softwareengineering.stackexchange.com/questions/342757/sharing-parts-of-a-monorepo) suggest it's impossible to have granular access control within a monorepo.

**Comment by korfuri** [comment]
I've linked to a few "good reads" that touch on this. I'm reluctant to include such a discussion in the list itself, as the mono vs multi repo debate has lots of good points on both sides and these arguments tend to devolve into dogma pretty quickly when they're in a public setting (or even within one team: I find it's a guaranteed way to make lunchtime discussions more lively).

If you have good articles on the topic I'm happy to add them to the list.
