### ISSUE TITLE
Add wsrun

### ISSUE THREAD

**Issue by jonaskello** [korfuri/awesome-monorepo#6]
The [wsrun](https://github.com/whoeverest/wsrun) package can be used in monorepos using yarn workspaces. Please consider adding it to the list.

**Comment by korfuri** [comment]
Hi, I don't quite understand this tool, what category would you fit it in?

**Comment by jonaskello** [comment]
It can be used in combination with yarn workspaces in order to run scripts in package.json. Let's say I have this in package.json for all the packages in my monorepo:

```
scripts: {
  "build": "some build command for this package"
}
```

Then I can do `wsrun build` and it will run that package.json script for all packages in the monorepo. You can also make it run in order of dependency, so it builds the packages that have no dependencies on other packages in the monorepo first etc. Of course it can run any script command not just build.

Lerna has the same thing with [lerna run](https://github.com/lerna/lerna#run) but wsrun has more options. Since running commands is the only thing wsrun does it can focus on it more than lerna which is a all purpose tool. I usually use wsrun in monorepos where I don't need to publish anything, so then I don't need lerna but I still need to run commands.

If you are familiar with [npm-run-all](https://www.npmjs.com/package/npm-run-all), then you can think of wsrun as the same thing but for multiple packages in a monorepo.

So I guess I would place it at the same place as lerna or oao, in either "Repository management tools" or "Build systems & dependency management tools".

The short description of wsrun from the developers repo is "Command runner for Yarn workspaces. Dependency aware."

**Comment by korfuri** [comment]
Sounds great, adding :) Thanks!
